[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
flate2 = "1.0.24"
actix-web = "4"
futures-util = "0.3"
uuid = { version = "1.0", features = ["serde", "v4"] }
actix-cors = "0.6"
actix-multipart = "0.4"
